### PR TITLE
Fixed include error in Visual Studio

### PR DESCRIPTION
**Pull request by Agamnentzar**

### CODE REVIEW

**Comment by zbjornson** [comment]
Just realized I duplicated this PR.

Transferring comment: The patch committed in #574 seems to have broken the build on windows. This commit adds another include dir for windows.

**Comment by LinusU** [comment]
I would love it if I could get some help testing this since I don't have access to a windows environment. The following command should do the trick:

```sh
npm install Agamnentzar/node-canvas#8aa52be
```

**Comment by timknip** [comment]
@LinusU 
```
npm install Agamnentzar/node-canvas#8aa52be
```
installs fine on win8.1-x64 (node 0.12.7, npm 2.11.3)

**Comment by LinusU** [comment]
Thank you!

**Comment by richdunajewski** [comment]
Confirming that this also works for me. Since you just merged this in to master a few minutes ago, I just added the following to my **package.json** under dependencies:

```"canvas": "https://github.com/Automattic/node-canvas/tarball/60b1fbceb699f8f88d64dd97ab906756abeb8ed3"```

**Comment by LinusU** [comment]
`1.2.6` is up on npm now with this fix! Scary pushing my first release of `canvas` but I think everything went well :)

If you would like to change to `"canvas": "^1.2.6"` and see that it works I would appreciate it :+1:

**Comment by Agamnentzar** [comment]
Works great, thank you :)

**Comment by LinusU** [comment]
Great :fireworks: no problem

**Comment by timknip** [comment]
Updated [canvas-browserify](https://github.com/dominictarr/canvas-browserify) to use ```canvas@^1.2.7```.

All ok on win8

**Comment by LinusU** [comment]
Super :ok_hand:

**Comment by LinusU** [comment]
@timknip Would it be cool to include `browserify` support out of the box from this package? I don't see any downside to it...

**Comment by timknip** [comment]
@LinusU Well, i'm just the maintainer of ```canvas-browserify``` by accident ;-) 
And I really don't know much about the workings of ```browserify```.

My guess this is all that's needed: https://github.com/dominictarr/canvas-browserify/blob/master/browser.js

ie: ```browser.js``` overrides Canvas and Image of ```canvas``` ... something like that.

Would be trivial to test... but not sure if i can find time now

**Comment by dominictarr** [comment]
yeah, it should just return something that wraps the browser Canvas object, and creates usable canvas for you in the same manner that node-canvas does...

**Pull request merged**
