### PR TITLE
readme: update installation instructions

### PR DESCRIPTION
**Pull request by LinusU**
See discussion in #651

Preview:

OS | Command
----- | -----
OS X | `brew install pkg-config cairo libpng jpeg giflib`
Ubuntu | `sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++`
Fedora | `sudo yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel`
Solaris | `pkgin install cairo pkg-config xproto renderproto kbproto xextproto`
Windows | [Instructions on our wiki](https://github.com/Automattic/node-canvas/wiki/Installation---Windows)

### CODE REVIEW

**Comment by dbkaplun** [comment]
```
$ npm install canvas

 08:45:00  dan.kaplun@N164MALT:~ 
$ brew install pkg-config cairo libpng jpeg giflib
Warning: pkg-config-0.29 already installed
Warning: cairo-1.14.2_1 already installed
Warning: libpng-1.6.18 already installed
Warning: jpeg-8d already installed
Warning: giflib-4.2.3 already installed

 08:45:13  dan.kaplun@N164MALT:~ 
$ npm install canvas

> canvas@1.3.0 install /Users/dan.kaplun/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dan.kaplun/node_modules/canvas
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN ENOENT ENOENT: no such file or directory, open '/Users/dan.kaplun/package.json'
npm WARN EPACKAGEJSON dan.kaplun No description
npm WARN EPACKAGEJSON dan.kaplun No repository field.
npm WARN EPACKAGEJSON dan.kaplun No README data
npm WARN EPACKAGEJSON dan.kaplun No license field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dan.kaplun/npm-debug.log
```

**Comment by LinusU** [comment]
Oh, I remember that error, have you upgraded your computer to El Capitan?

This isn't a problem with canvas per se, it has something to do with OS X not having a `/use/local/include` dir at all by default. I don't remember how to fix it though.

Could you try `xcode-select --install`?

**Comment by dbkaplun** [comment]
`xcode-select --install` worked. LGTM

**Comment by LinusU** [comment]
Just to clarify what happened; when upgrading to El Capitan the clang compiler stops looking in `/usr/local`. This is not a problem with node-canvas and will affect *any stuff* that's being built with clang.

I'm going to give the other maintainers some time to say something and then I'll merge.

@kangax Any comments?

**Comment by kangax** [comment]
LGTM (although I'm only familiar with OS X)

**Comment by LinusU** [comment]
Okay, merging this now :+1:

**Pull request merged**
