### PR TITLE
Backends support

### PR DESCRIPTION
**Pull request by piranna**
This is a stripped-down version of pull-request #571 focused only on the
backends support, but adding also support for PDF and SVG backends and
passing the tests. it also retain backwards compatibility with the old API,
so this would be easy to merge since it's mostly to move around the PDF and
SVG code and checks to independent classes. There's some code for
`pdfStream` and similar methods that I think they should be moved too since
they are mostly backend specific, and make more sense there. I didn't do
that since it would break the API, but maybe it would be added some
functions on the Canvas object that proxy the petitions to the backend to
retain compatibility.

I know it's a big pull-request, so I'm open for comments over it.

### CODE REVIEW

**Comment by piranna** [comment]
Any update on this one?

**Comment by cammanderson** [comment]
This seems promising! :+1:

**Comment by piranna** [comment]
> This seems promising!

I'm glad you liked it, let's hope if it gets merged soon :-)

**Comment by ianmetcalf** [comment]
@piranna I couldn't get the example to work, `Canvas.backends` was undefined. I got it to work by adding the initialization of `backends` on the target object in init.cc

```js
NAN_MODULE_INIT(init) {
  Backends::Initialize(target);
  Canvas::Initialize(target);
  Image::Initialize(target);
```

https://github.com/ianmetcalf/node-canvas/blob/27a48c66f8ad1cd642377d5afd74d230efbab0aa/src/init.cc#L28

**Comment by piranna** [comment]
You are right, I missed it :-P It doesn't matter too much since this
pull-request just prepare the backends mechanism and only offer the current
internal ones, so the current API doesn't change. When this got merged then
I'll move forward other ones from my previous pull-request to add support
for fbdev and X11, and in that case the Backends namespace will be needed.

**Comment by ianmetcalf** [comment]
I just pointed it out since this PR includes `examples/backends.js` which uses this new API. It would probably be good to either update `init.cc` or change the example to use the exiting API.

I really appreciate the work you did abstracting the backends. I'm currently working with the FBDev backend that I extracted from your master branch.

**Comment by piranna** [comment]
> I just pointed it out since this PR includes examples/backends.js which uses this new API. It would probably be good to either update init.cc or change the example to use the exiting API.

You are right. Since it's the new behaviour, I've added the missing namespace.


> I really appreciate the work you did abstracting the backends. I'm currently working with the FBDev backend that I extracted from your master branch.

Well, I have just only updated some previous code to use it with static builds for NodeOS :-P So why are you using it? Are you using it on production?

**Comment by piranna** [comment]
Any update on this? Can we merge it?

**Comment by piranna** [comment]
Ping?

**Comment by LinusU** [comment]
Awesome work! Sorry for the long delay 🎉

**Comment by piranna** [comment]
Thank you for merging :-)

**Comment by ReneHollander** [comment]
I am a bit saddened by the fact, that there is no mention of my work on this. Just found out through coincidence, that this got merged two years after I made my first commit to my fork.

**Comment by chearon** [comment]
You were mentioned in the original PR #571

**Comment by piranna** [comment]
@ReneHollander you are right, the foundational code of this pull-request is based on your work, without it I would have not been able to know how to do it, thanks :-)

**Comment by piranna** [comment]
I hope now that this got merged, if static builds support gets merged too, since now Github better support pull-requests merges without need to do rebases that we could re-use the previous pull-request as a container for several of the backends, so your work would have a direct repercusion on the node-canvas code :-)

**Pull request merged**
