### PR TITLE
Update nan

### PR DESCRIPTION
**Pull request by zbjornson**
v14 requires 2.14.1. The semver range in package.json already allowed for that version, but this requires at least that version.

None of the other changes (2.14.2, 2.15.0) matter for us.

- [x] Have you updated CHANGELOG.md?

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
👍

**Comment by omerts** [comment]
Still getting Canvas.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __c 

In both node 14 & 16

**Comment by zbjornson** [comment]
@omerts please open a new issue with more info, that's unrelated to this PR.

**Comment by semireg** [comment]
Did a new issue get opened for this @omerts?

I'm seeing this when building on master with electron 16.

```
"...\app\node_modules\canvas\build\binding.sln" (default target) (1) ->
"...\app\node_modules\canvas\build\canvas-postbuild.vcxproj.metaproj" (default target) (2) ->
"...\app\node_modules\canvas\build\canvas.vcxproj" (default target) (3) ->
(Link target) ->
  Canvas.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v
8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ) referenced in function "void __cdecl parsePNGArgs(class v8::Local<class v8::Value>,struct PngClosure &)" (?parsePNGArgs@@YAXV?$Local@VValue@v8@@@v8@@AEAUPngClosure@@@Z)
 [...\app\node_modules\canvas\build\canvas.vcxproj]
  CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingS
tore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ) [...\app\node_modules\canvas\build\canvas.vcxproj]
  ImageData.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffe
r@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ) [...\app\node_modules\canvas\build\canvas.vcxproj]
  ...\app\node_modules\canvas\build\Release\canvas.node : fatal error LNK1120: 1 unresolved externals [...\app\node_modules\canvas\build\
canvas.vcxproj]```

**Comment by woestler** [comment]
@semireg 
Hi, have you get this fixed ? I have the same problem. thanks.

**Comment by linqian02** [comment]
the same problem.

**Pull request merged**
