### PR TITLE
Added support for Freetype, JPEG, Giflib, and Pango on Windows

### PR DESCRIPTION
**Pull request by sepehr-laal**
I have only tested this with Visual Studio 2013 (Update 5) x64 build. Following versions of dependencies I have used:
- [GTK+ 2.22.1 bundle](http://gemmei.acc.umu.se/pub/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip)
- [Freetype 2.6](http://superb-dca2.dl.sourceforge.net/project/freetype/freetype2/2.6/freetype-2.6.tar.bz2)
- [GifLib 5.1.1](http://superb-dca2.dl.sourceforge.net/project/giflib/giflib-5.1.1.tar.bz2)
- [LibJpeg Turbo 1.4.1](http://skylineservers.dl.sourceforge.net/project/libjpeg-turbo/1.4.1/libjpeg-turbo-1.4.1-vc64.exe)

Note that I have not used the same Freetype that comes with GTK+, because it was slightly outdated and I would rather building Freetype from scratch since it uses CMake and it takes literally two minutes to build and install it. After installation `include/freetype2` needs to be renamed to `include/freetype`.

Giflib comes with `autoconf` scripts for its build management. Honestly the easiest way to build it, is just including it in the source tree. That's how [Leptonica](http://www.leptonica.org/vs2008doc/building-image-libraries.html) builds it as well.

### CODE REVIEW

**Comment by sepehr-laal** [comment]
Almost forgot, two other things needed to be added in order to get the compilation going:

 1. A dummy `unistd.h` for Freetype and GifLib.
 2. An implementation for `strndup` on Windows.

**Comment by terrancesnyder** [comment]
Holy font batman! +1000 on this.

**Comment by iongion** [comment]
+1K - I couldnt use node-canvas on windows if not for this issue, mentioning the proper prebuilt GTK bundle

**Comment by LinusU** [comment]
@sepehr-laal would you mind rebasing on latest master?

**Comment by chearon** [comment]
> +1K - I couldnt use node-canvas on windows if not for this issue, mentioning the proper prebuilt GTK bundle

It's mentioned on the wiki [here](https://github.com/Automattic/node-canvas/wiki/Installation---Windows). Is this PR still relevant? I didn't think there was anything wrong with the Windows build.

**Comment by zbjornson** [comment]
GIF support maybe? But if it's added, it should probably be optional like JPEG and SVG.

**Comment by sepehr-laal** [comment]
@LinusU it's been a long time since I looked at this PR. I know of a handful of companies and individuals who have production code off of this PR. If you don't mind, I am going to submit a new PR and close this as is for historical references.

**Comment by LinusU** [comment]
Sounds good 👍

**Comment by zbjornson** [comment]
Closing per:
> I am going to submit a new PR and close this as is for historical references.

**Pull request closed without merging**
