### PR TITLE
Fix putImageData(data, neg, neg)

### LINKED ISSUE #962: `putImageData(imageData, -1, -1)` segfaults
Tested using canvas@2.0.0-alpha.2 (with the latest master branch) and Node.js v8.2.1.

Test case:

```js
const Canvas = require('canvas');

const canvas = new Canvas(1, 1);
const context = canvas.getContext('2d');
const imageData = new ImageData(2, 2);
context.putImageData(imageData, -1, -1);
```

What I want to do is to crop an image using a canvas. It should draw the image start from point [1, 1] but not segfault.

$ node test.js
```shell
*** Error in `/usr/bin/nodejs': free(): invalid next size (fast): 0x0000562dcf9deb60 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7908b)[0x7fdf92e8d08b]
/lib/x86_64-linux-gnu/libc.so.6(+0x82c3a)[0x7fdf92e96c3a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fdf92e9ad2c]
/usr/bin/nodejs(_ZN2v88internal18ArrayBufferTracker7FreeAllEPNS0_4PageE+0xd3)[0x562dcd92aec3]
/usr/bin/nodejs(_ZN2v88internal9SemiSpace8TearDownEv+0x58)[0x562dcd99db18]
/usr/bin/nodejs(_ZN2v88internal8NewSpace8TearDownEv+0x6e)[0x562dcd99db9e]
/usr/bin/nodejs(_ZN2v88internal4Heap8TearDownEv+0x2f9)[0x562dcd949089]
/usr/bin/nodejs(_ZN2v88internal7Isolate6DeinitEv+0x1d9)[0x562dcda26509]
/usr/bin/nodejs(_ZN2v88internal7Isolate8TearDownEv+0x53)[0x562dcda26773]
/usr/bin/nodejs(_ZN4node5StartEP9uv_loop_siPKPKciS5_+0xeee)[0x562dcde9695e]
/usr/bin/nodejs(_ZN4node5StartEiPPc+0x111)[0x562dcde90251]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7fdf92e343f1]
/usr/bin/nodejs(_start+0x2a)[0x562dcd2bd7ea]
======= Memory map: ========
3ca2d00000-3ca2d80000 rw-p 00000000 00:00 0 
ef52a00000-ef52a80000 rw-p 00000000 00:00 0 
```

See: 
1. https://github.com/Automattic/node-canvas/issues/749
1. https://github.com/Automattic/node-canvas/pull/750/commits/21dd24cc59f64e4f975cac1a5e675887f8d3aa8b

I believe it's related to the `memcpy()` operations at here: https://github.com/Automattic/node-canvas/blob/947f3a43a816e3f3a16e099ea04c459323335079/src/CanvasRenderingContext2d.cc#L720-L739

### PR DESCRIPTION
**Pull request by zbjornson**
Fixes #962
Closes #963

(Pending @zixia trying it out hopefully.)

### CODE REVIEW

**Comment by zbjornson** [comment]
I don't know why neither @zixia nor myself can get the unit tests to segfault, but when I added a visual test with the exact same code, I got the segfault. 🤷‍♂️

Anyway, confirmed that this PR fixes the segfault and added that visual test.

image

**Comment by zixia** [comment]
Awesome, maybe it's because segfault  needs actual copy the data .

Btw your code looks so clean! 👍

**Comment by LinusU** [comment]
Thanks!

**Comment by LinusU** [comment]
Thanks!

**Comment by LinusU** [comment]
Published in `2.0.0-alpha.5`

**Pull request merged**
