### PR TITLE
[cleanup] feat(prebuild): support of Alpine binaries

### PR DESCRIPTION
**Pull request by Delagen**
- update dependencies
- rework binding.gyp
- rework msys bundle for Windows
- add bundle for MUSL (Alpine)
- rework bundle scripts and ci

Thanks for contributing!

- [ ] Have you updated CHANGELOG.md?

### CODE REVIEW

**Comment by Delagen** [comment]
Some issues with test on Alpine Linux
https://github.com/Delagen/node-canvas/actions/runs/8421478461/job/23058526480#step:6:268
3 tests failed ( concerning measureText (but may be it normal)

Pipeline reworked to create tag named vX.Y.Z, will be created prerelease and all artifacts will be uploaded to it.
After this you can rewrite it as you wish.

Added comments in workflows for continue-on-error (failed tests on windows(node20) and alpine).
Added commented matrix for macOS ARM based, but seems it need special worker somewhere or some payed account

**Comment by Delagen** [comment]
Example of generated assets
https://github.com/Delagen/node-canvas/releases/tag/v3.0.1

**Comment by Delagen** [comment]
Need to rewrite Wiki articles for building on Windows to remove manual download of libraries and use only MSYS case.

1. Install MSYS
2. Launch in UCRT64 system (with path-type: inherit)
3. Install dependencies, gen definitions manually or simply run `. ./prebuild/Windows/preinstall.sh`
4. `npm install --build-from-source` or `npm rebuild` (in MSYS environment). 
That's all.
5. Run `. prebuild/Windows/bundle.sh` to copy all needed dll into build folder to remove dependency of MSYS env.

**Comment by zbjornson** [comment]
Thanks for preparing this!

I really need to delete the prebuilds directory in the master branch -- prebuilds are made using the `prebuilds` branch, and you're not the first person to try to use the master branch (https://github.com/Automattic/node-canvas/pull/2354#issuecomment-1971687677). Sorry about that. As noted in that comment, we're blocked on making prebuilds to work with N-API right now...

**Comment by Delagen** [comment]
@zbjornson Thanks for comment, clean up this MR, and will open new on Prebuilds target

**Comment by chearon** [comment]
Superseded by #2370

**Pull request closed without merging**
