### PR TITLE
Propagate async context

### PR DESCRIPTION
**Pull request by kkoopa**
Thanks for contributing!

- [N] Have you updated CHANGELOG.md?

### CODE REVIEW

**Comment by zbjornson** [comment]
@kkoopa Your original commit got rid of (or came before?) the deprecation warnings for `Nan::MakeCallback`, but since updating this branch with master, the warnings are back. I also tried this branch with nan 2.4.0, but [the warnings remain](https://travis-ci.org/zbjornson/node-canvas/jobs/356604738#L637). Is this PR supposed to fix them?

**Comment by kkoopa** [comment]
That is a (slightly) different set of deprecation warnings. However, they would fall within the scope of this PR, since they also are related to async context propagation. I will add a commit when I have time.

**Comment by kkoopa** [comment]
That should do it. Not the most elegant solution, but I am not rewriting that closure callback mess.

**Comment by zbjornson** [comment]
Sweet, thanks @kkoopa!

**Pull request merged**
