### PR TITLE
Avoid permissions error in Vagrant

### PR DESCRIPTION
**Pull request by tranzium**
Vagrant + Windows can prevent file permission changes

### CODE REVIEW

**Comment by zbjornson** [comment]
This looks closely related to the first commit in #754 and subject to the same issues. But I don't understand how this is a Windows problem -- the change is in the non-Windows part of the binding file -- can you explain that please?

**Comment by tranzium** [comment]
From what I could diagnose, changes to the file's permissions (including +x) could not be applied, thus the util script could not be executed for the install.

Using both chmod and chown result in the file being the exact same.

Although this could be a Vagrant issue, I made the changes in the assumption that one was not able to change their Vagrant configuration.

**Comment by zbjornson** [comment]
I see, thanks for the info. I'm still not quite clear if this relates to Windows (mentioned in the commit message but not the PR title). Are you using a set of extensions on top of Windows to get `chmod` and `chown`, or are you actually running on a linux distro?

**Comment by tranzium** [comment]
I am running Ubuntu in Vagrant (virtual machine).
I will test adjusting the sync_folder permissions and see if I can get the /util/has_lib.sh script running directly from a `npm install canvas` call. Will report any further findings.

**Comment by LinusU** [comment]
This script has been migrated to node now so I don't think this should be a problem anymore...

**Pull request closed without merging**
