### PR TITLE
Add M1 compiling note

### PR DESCRIPTION
**Pull request by infodusha**
I have not you updated CHANGELOG.md, because of that is just doc change.

The change was got from the issue #528

### CODE REVIEW

**Comment by LinusU** [comment]
Hmm, I'm using an M1 and I don't need to run `arch -arm64` in front of brew 🤔 

Are you sure that your Homebrew is setup correctly? Is there any more background on why one would want to have that in front?

**Comment by LinusU** [comment]
I'm not sure, what happens if you run `brew` without `arch -arm64`?

**Comment by infodusha** [comment]
It installs all the deps fine but the error that present in the issue i mentioned still presents

**Comment by infodusha** [comment]
That could be, i don't actually know how homebrew works with Rosetta

**Comment by infodusha** [comment]
Can we pause that for a while, i am going to dig into details and versify my thoughts

**Comment by MetaverseMan** [comment]
with respect to all you bros ,I'm using an M1 ,Monterey 12.4, and I am already prepared mentally to use the second way "arch -arm64 brew ..."to  figure out ,but when i just  try it with no "arch -arm64" in front of brew, it works, so i think we can just try another when the first method we choose to use didn't work.

**Pull request closed without merging**
