### PR TITLE
Add support for ellipse method

### PR DESCRIPTION
**Pull request by zbjornson**
Simple addition to support `context2d.ellipse`.

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/ellipse

### CODE REVIEW

**Comment by LinusU** [comment]
Looking great as always! Thank you

**Comment by zznan0o0** [comment]
excuse me ellipse has been deleted？

**Comment by zbjornson** [comment]
@zznan0o0 it's only in 2.0.

**Comment by LinusU** [comment]
I'd be happy accept a pull request to the 1.x branch if anyone wants to backport it

**Pull request merged**
