### PR TITLE
using node-pre-gyp on windows

### PR DESCRIPTION
**Pull request by wsw0108**

### CODE REVIEW

**Comment by LinusU** [comment]
`Could not resolve host: maptalks.org`

**Comment by wsw0108** [comment]
For now, I have no public storage to place it.
I will get one and change the remote host.

**Comment by LinusU** [comment]
I think that this needs to be hosted by Automattic in a more official way. This is binary code that will be run on the end users machine after all.

**Comment by wsw0108** [comment]
I agree that. Hope it will be come soon.

**Comment by LinusU** [comment]
I think we still can have this open. If we manage to get everything in place so that it works, we can resolve the hosting issue later.

We must think about all the libraries that we are using though, would it be feasible to bundle cairo, pango, libpng, etc?

**Comment by Mithgol** [comment]
@wsw0108 If you do not have a cloud storage in your avail, for now consider hosting binaries in a content-addressable distributed file system — [IPFS](https://ipfs.io/).

**Pull request closed without merging**
