### PR TITLE
Don't rely strictly on code 200 for success

### PR DESCRIPTION
**Pull request by InventivetalentDev**
Thanks for contributing!

- [x] Have you updated CHANGELOG.md?

### CODE REVIEW

**Comment by loretoparisi** [comment]
@InventivetalentDev could this strict HTTP Code handling related to https://github.com/Automattic/node-canvas/issues/1389?
Thank you.

**Comment by InventivetalentDev** [comment]
@loretoparisi Yeah, redirects shouldn't be throwing errors either... Not sure if the internal request handling supports redirects though, so I'm not gonna change anything regarding that for now.

**Comment by loretoparisi** [comment]
@InventivetalentDev so the problem is the internal module making HTTP requests?

**Comment by loretoparisi** [comment]
@zahhakrnch yes I get your point. So in the meanwhile I just did like this

```javascript
self.download(pathOrUrl, temp)
                        .then(path => {
                            // feed images
                            const img = new Image()
                            img.onload = () => {

                                // create Canvas from Image
                                const width = self._options.model.imageWidth;
                                const height = self._options.model.imageHeight;
                                const canvas = createCanvas(width, height);
                                const ctx = canvas.getContext('2d');
                                ctx.drawImage(img, 0, 0, width, height);
                            }
                            img.onerror = err => { throw err }
                            img.src = path;
                        })
                        .catch(error => {
                            return reject(error);
                        })
```

where

```javascript
this.download = (uri, filename) => {
                return new Promise((resolve, reject) => {
                    request.head(uri, (err, res, body) => {
                        request(uri).pipe(fs.createWriteStream(filename))
                        .on('close', function () {
                            return resolve(filename);
                        })
                        .on('error', function (error) {
                            return reject(error);
                        });
                    });
                });
```

using `request` that will handle redirects seamless.

**Comment by LinusU** [comment]
This was addressed in #1398, please let me know if there is anything more missing :)

**Comment by loretoparisi** [comment]
@LinusU just to be clear, this means that there is no need anymore to manually fetch so now I can just do ` img.src = path;`?

**Comment by LinusU** [comment]
Yeah, it should handle redirects and all 2xx status codes now!

**Pull request closed without merging**
