### PR TITLE
Shadow blur

### PR DESCRIPTION
**Pull request by woodcoder**
This pull request
   1. adds a test showing how the shadowOffset{X,Y} values shouldn't be affected by the current transform
   2. fixes the shadowOffset{X,Y} translate to not be affected by the current transform matrix
   3. adds a 'PDF' button to the test-server output for easier comparison with PDF output
   4. creates an image buffer for blurred shadows so that they work with the vector-based PDF output
   5. adjusts the blur radius to more closely match the browser's implementation
   6. adjusts the shadowOffset slightly to more closely match the browser's output

It introduces minor regressions in the following tests:
   * *shadow globalAlpha* -- this shadow is not as definite as before (possibly because of multiple applications of the globalAlpha?)
   * *shadow strokeText()* -- this shadow is bolder than before (possibly due to the resolution of the shadow image buffer not matching the destination image?)

However, the other shadow tests all look much better (especially *shadowBlur values*) when compared against Firefox.

### CODE REVIEW

**Comment by kangax** [comment]
Thanks @woodcoder, this looks nice. It will probably fix https://github.com/Automattic/node-canvas/issues/467 Any chance to also take care of https://github.com/Automattic/node-canvas/issues/133 with this PR?

**Comment by woodcoder** [comment]
Just had a really quick look at #133 and written a test for it.  Fixing it looks like we'd need to do something like fix up `DrawImage` to do the following if it has a shadow:
   1. get the image as alpha-channel only (using a CAIRO_CONTENT_ALPHA surface?)
   2. render that to a temporary image surface (as in this PR)
   3. pass that to blur (if blurring) and
   4. then paint it.

**Comment by woodcoder** [comment]
This provides a non-blurred image shadow (but respecting any alpha in the image) by using the image as a mask for the shadow colour.  Hopefully that'll get you closer!

**Comment by kangax** [comment]
@woodcoder nice, thanks!

/cc @rvagg @TooTallNate

**Comment by rvagg** [comment]
lgtm I think, my only question would be whether this is a feature addition (minor version bump) or is there stuff in here that would constitute a breaking change (major version bump)?

**Comment by kangax** [comment]
I would consider this is a bug fix. The fact that shadow didn't work for images was not documented and was just a limitation of previous implementation.

**Comment by woodcoder** [comment]
This last commit fixes the two regressions I noticed in the _shadow globalAlpha_ and _shadow strokeText()_ tests -- it was because the line (stroke) width was not being respected when drawing the shadow.  There may be more drawing settings like this that need to be copied between the contexts, but I'm not familiar enough with cairo to know if there's a quick way of doing this.

**Comment by kangax** [comment]
I suppose I'm gonna pull this in.

**Comment by woodcoder** [comment]
Thank you!

One thing I've noticed since, is that I use `cairo_surface_create_similar_image` which was introduced in cairo 1.12.  This may cause issues on Windows installs because the version of cairo in GTK+ is 1.10.

I'm not sure if that'll be a problem going forward, but it's possible to use `cairo_image_surface_create` instead, as shown here:
https://github.com/woodcoder/node-canvas/commit/c2de36ac986e03fa7f8810bda487cae42d50f39c

**Pull request merged**
