### PR TITLE
Fix compilation on Visual Studio 2015

### PR DESCRIPTION
**Pull request by Agamnentzar**
Fix for issue #605 as suggested by @LinusU

### CODE REVIEW

**Comment by LinusU** [comment]
Build failed because of npm/npm#9633, restarting now...

I think this looks good but we need to test manually since we don't build for windows in the cloud. Any volunteers?

ping @zbjornson 

btw. is anyone familiar with setting up AppVeyor for an open source project?

**Comment by LinusU** [comment]
Oh and, @Agamnentzar would you mind squashing your commits to one?

**Comment by Agamnentzar** [comment]
Done :)

**Comment by LinusU** [comment]
Thank you :+1:

**Comment by LinusU** [comment]
Could you also state which version of Windows and which version of Visual Studio you have tried building with?

**Comment by Agamnentzar** [comment]
Tested it on Windows 10 with VS2015 and VS2013

**Comment by LinusU** [comment]
Super :+1:

**Comment by zbjornson** [comment]
Original problem verified, fix confirmed, Win7/VS2015. :+1:

**Comment by LinusU** [comment]
I have manually tested this on Node.js 5.x on OS X as well, merging now :+1: 

Thanks for the help on this guys! :fireworks:

**Comment by LinusU** [comment]
Released as 1.3.3.

**Pull request merged**
