### PR TITLE
Prebuild binaries for Node 20

### PR DESCRIPTION
**Pull request by hargasinski**
Node 20 was recently released. This PR adds support for it to ci.

- [X] Have you updated CHANGELOG.md?

### CODE REVIEW

**Review by zbjornson — APPROVED** [review]
Great to have it in CI, thanks.

prebuild.yaml is used in the prebuilds branch, not the master branch, but we can update that next time we make prebuilds.

**Comment by hargasinski** [comment]
It looks like one of the linux tests failed, but it looks like it's related to a timeout.

> prebuild.yaml is used in the prebuilds branch, not the master branch, but we can update that next time we make prebuilds.

Is there anything I could help with?

**Comment by zbjornson** [comment]
I'll try to start the prebuilds for Node 20 now. Thanks!

**Comment by zbjornson** [comment]
Prebuilds done for [v2.11.2](https://github.com/Automattic/node-canvas/releases/tag/v2.11.2)!

**Comment by hargasinski** [comment]
> Prebuilds done for [v2.11.2](https://github.com/Automattic/node-canvas/releases/tag/v2.11.2)!

Great, thanks!

**Pull request merged**
