### PR TITLE
Wrap std::min calls in paranthesis to prevent macro expansion on windows

### LINKED ISSUE #659: Error compiling CanvasRenderingContext2d.cc using VS2013
There seems to be an issue with std::min conflicting with the min macro defined by windows.h, same issue as [explained here](http://stackoverflow.com/questions/5004858/stdmin-gives-error). I dont have the error output available right now, but let me know if you want to see it.

I'm building using nw-gyp (as opposed to node-gyp) for usage with node-webkit, which may be part of the issue.

I propose we use [this solution](http://stackoverflow.com/a/22023122). I'll send a pull request in a minute.

### PR DESCRIPTION
**Pull request by deadbeef84**
Fixes #659.

### CODE REVIEW

**Comment by LinusU** [comment]
Hmm, that's strange...

@zbjornson Any comments on this? I'm okay with merging it otherwise

**Comment by zbjornson** [comment]
I don't see this issue using node-gyp with either VS2013 or 2015, but also no problem merging. (I tried reproducing with nw-gyp, but couldn't get nw-gyp to run. Wonder if this happens with electron, too.) Curious what's including windows.h or windef.h and causing this problem.

Might add a comment saying why the otherwise unnecessary parens are there so they aren't removed accidentally in the future.

**Comment by LinusU** [comment]
That sounds good, @deadbeef84 could you add a comment to the code?

**Comment by deadbeef84** [comment]
Sure!

Btw, I'm using VS2013 express if that makes any difference.

**Comment by LinusU** [comment]
Is there a reason why we aren't using the `#define NOMINMAX` fix instead?

**Comment by deadbeef84** [comment]
Not really, I just thought parens were less hacky, but I guess they're both a bit hacky :) If you want me to change to `#define NOMINMAX` I'll do that. Perhaps we could even put the define in [binding.gyp](https://github.com/deadbeef84/node-canvas/blob/windows-std-min-fix/binding.gyp#L66), if you prefer that?

**Comment by LinusU** [comment]
I think I would prefer it in the binding.gyp for windows only. I feel like we would never want to use the `min` macro since we now have `std::min` function.

Maybe the binding.gyp can do it conditionally only for VS2013 Express...

Or maybe it's better to have `#define NOMINMAX` before the `#include <windows.h>`, it makes it clear what it's for.

**Comment by deadbeef84** [comment]
Except windows.h is not included directly from node-canvas, but probably by one of the libraries. Which is also why I prefer the parens-solution, assume any of the libraries use the min/max macros in their header-files, then defining NOMINMAX would break them.

**Comment by deadbeef84** [comment]
Any thoughts?

**Comment by LinusU** [comment]
Sorry for the delay, I hate problems like this :)

Could you duplicate the comment to the other callsite as well, then I'll merge :+1:

**Comment by deadbeef84** [comment]
I know what you mean :) Thanks!

**Comment by LinusU** [comment]
Released as `1.3.1`

**Pull request merged**
