### PR TITLE
add helper function to execute test and only fire callback once

### PR DESCRIPTION
**Pull request by inssein**
Fixes https://github.com/Automattic/node-canvas/issues/645

### CODE REVIEW

**Comment by LinusU** [comment]
I don't understand, how does this make sure that callbacks only fire once? Could you please explain your code :)

**Comment by inssein** [comment]
@LinusU I just wrote a simple testbed, and tested it in 4 different node versions. Looks like it never worked, or I am missing something.

```js
var done = function() {
  console.log('done');
};

var fn = function(ctx, done) {
  done();
};

2 == fn.length ? fn('test', done) : fn('test'), done();```

The above code will print ```done``` twice. Once by going through fn(), and once by being called at the end of the last line. This breaks the test for me as /jpeg and /render will try to send the result twice.

**Comment by LinusU** [comment]
Cool, yes I have seen this behaviour as well actually

**Comment by inssein** [comment]
@LinusU what's the process on getting this merged?

**Comment by LinusU** [comment]
Merging now, sorry for the delay

**Comment by inssein** [comment]
@LinusU thanks!

**Comment by LinusU** [comment]
Thank you, help is always appreciated!

**Pull request merged**
