### PR TITLE
Don't #define snprintf on VS2015

### LINKED ISSUE #605: npm install canvas fails: Macro definition of snprintf conflicts with Standard Library function declaration
Hi,

I've installed VS2015 and I have a suspicion that this is due to this.

npm install canvas fails to build with errors:

```text
:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925):
 warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\Ca
nvasPattern.cc) [\node_modules\canvas
\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925
  ): note: command-line arguments:  see previous definition of 'snprintf' (comp
  iling source file ..\src\CanvasPattern.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927):
 fatal error C1189: #error:  Macro definition of snprintf conflicts with Standa
rd Library function declaration (compiling source file ..\src\CanvasPattern.cc)
 [\node_modules\canvas\build\canvas.v
cxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925):
 warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\Ca
nvasGradient.cc) [...\node_modules\canva
s\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925
  ): note: command-line arguments:  see previous definition of 'snprintf' (comp
  iling source file ..\src\CanvasGradient.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927):
 fatal error C1189: #error:  Macro definition of snprintf conflicts with Standa
rd Library function declaration (compiling source file ..\src\CanvasGradient.cc
) [...\node_modules\canvas\build\canvas.
vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925):
 warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\Ca
nvas.cc) [...\\node_modules\canvas\build\
canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925
  ): note: command-line arguments:  see previous definition of 'snprintf' (comp
  iling source file ..\src\Canvas.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927):
 fatal error C1189: #error:  Macro definition of snprintf conflicts with Standa
rd Library function declaration (compiling source file ..\src\Canvas.cc) [...\\node_modules\canvas\build\canvas.vcxproj]
  color.cc
  Image.cc
  ImageData.cc
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925):
 warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\co
lor.cc) [...\node_modules\canvas\build\c
anvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925
  ): note: command-line arguments:  see previous definition of 'snprintf' (comp
  iling source file ..\src\color.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927):
 fatal error C1189: #error:  Macro definition of snprintf conflicts with Standa
rd Library function declaration (compiling source file ..\src\color.cc) [...\node_modules\canvas\build\canvas.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925):
 warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\Im
age.cc) [...\node_modules\canvas\build\c
anvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925
  ): note: command-line arguments:  see previous definition of 'snprintf' (comp
  iling source file ..\src\Image.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927):
 fatal error C1189: #error:  Macro definition of snprintf conflicts with Standa
rd Library function declaration (compiling source file ..\src\Image.cc) [...\dominantcolor\node_modules\canvas\build\canvas.vcxproj]
  init.cc
```

I've seen this post

http://stackoverflow.com/questions/27754492/vs-2015-compiling-cocos2d-x-3-3-error-fatal-error-c1189-error-macro-definiti

but this requires source changes.

Or is there another way to have this successfully installed?

Thanks.

### PR DESCRIPTION
**Pull request by oliversalzburg**
I hope this is the appropriate fix. At least now it compiles with 2015 for me.
Fixes #605

### CODE REVIEW

**Comment by oliversalzburg** [comment]
Great, that only created *more* problems :P No idea how to properly resolve this. I have pretty much zero knowledge of gyp.

**Comment by zbjornson** [comment]
I think you're looking for `_MSC_VER == 1900` (VS2015). I think it's preferable to actually detect the macro instead of the compiler version though, using Linus' method [here](https://github.com/Automattic/node-canvas/issues/605#issuecomment-127898601).

(Somehow I haven't encountered this problem with VS2012 or 2015...)

**Comment by oliversalzburg** [comment]
Well, the bigger problem seems to be that `gyp` will completely fail if the variable isn't defined at all, as shown on Travis. I don't know how to get around that.

**Comment by vansante** [comment]
If I read your changes correctly, you seem to have forgotten the non-windows case. So doing something like this should solve it:

```js
['OS=="win"' and 'MSVS_VERSION=="2015"', {
	'defines': [
			'_USE_MATH_DEFINES' # for M_PI
	],
}],
['OS!="win"' or 'MSVS_VERSION!="2015"', {
	'defines': [
		'snprintf=_snprintf',
		'_USE_MATH_DEFINES' # for M_PI
	]
}]
```

Disclaimer: I do not know anything about this project or gyp. I just ran into this as well ;)

**Comment by Agamnentzar** [comment]
Fixed the issue in code in #670

**Comment by oliversalzburg** [comment]
Closing in favor of #670. I have no idea how to fix this in gyp anyway :P

**Pull request closed without merging**
