### PR TITLE
Context2d has no export #1865 fix

### PR DESCRIPTION
**Pull request by Tolfx**
Simply added class `Context2d` and extends it with `NodeCanvasRenderingContext2D` to solve issue #1865

- [ ] Have you updated CHANGELOG.md?

### CODE REVIEW

**Comment by LinusU** [comment]
This file references the DOM typings which should have `Context2D`, that's why ours is called `NodeCanvasRenderingContext2D ` in the first place:

```ts
/// <reference lib="dom" />
```

I'm not sure that this is the correct fix 🤔 

-----

Hmm, after reading the issue you opened, I think that the correct fix would be either to rename `NodeCanvasRenderingContext2D` to `Context2D`, or do something like:

```diff
-export class NodeCanvasRenderingContext2D extends CanvasRenderingContext2D {
+export interface NodeCanvasRenderingContext2D extends CanvasRenderingContext2D {
```

```diff
+export class Context2D implements NodeCanvasRenderingContext2D
```

**Comment by Tolfx** [comment]
> This file references the DOM typings which should have `Context2D`, that's why ours is called `NodeCanvasRenderingContext2D ` in the first place:
> 
> ```ts
> /// <reference lib="dom" />
> ```
> 
> I'm not sure that this is the correct fix 🤔 
> 
> -----
> 
> Hmm, after reading the issue you opened, I think that the correct fix would be either to rename `NodeCanvasRenderingContext2D` to `Context2D`, or do something like:
> 
> ```diff
> -export class NodeCanvasRenderingContext2D extends CanvasRenderingContext2D {
> +export interface NodeCanvasRenderingContext2D extends CanvasRenderingContext2D {
> ```
> 
> ```diff
> +export class Context2D implements NodeCanvasRenderingContext2D
> ```
> 
> 

Due to not really understanding why it wasn't named `Context2D` I decided to do the way I did it. But your following method would work Indeed.

**Comment by Tolfx** [comment]
I tested and honestly I think renaming it to `Context2d` would be the best solution.

Because if just implementing `Context2d` with `NodeCanvasRenderingContext2D` it would still be an issue with types.
Since if I want to add new methods to the class I need to declare it, and because `.getContext()` returns `NodeCanvasRenderingContext2D` it would not have been changed.

```ts
declare module "canvas" {
    export interface Context2d {
        hello: string;
    }
}

Context2d.prototype.hello = "hello";

let canvas = createCanvas(width, height)
let ctx = canvas.getContext('2d'); // Returns NodeCanvasRenderingContext2D and not Context2d
console.log(ctx.hello) // undefined according to typescript
```

But by just renaming it to `Context2d` this issue will be solved as well.

```diff
- export class NodeCanvasRenderingContext2D extends CanvasRenderingContext2D
+ export class Context2d extends CanvasRenderingContext2D
```
*needs to rename everything ofc*

**Comment by zbjornson** [comment]
`Context2d

**Comment by zbjornson** [comment]
`Context2d` is a legacy name from v0/v1 that should be removed sometime. 
https://github.com/Automattic/node-canvas/blob/d7ebfcec12682bf7a57bca7aa98ed48398adf4bd/index.js#L61

`CanvasRenderingContext2d` is the name from the HTML Canvas specification and is what's actually exported.

`NodeCanvasRenderingContext2d` is the name of our types interface. I think it was a mistake to export this (https://github.com/Automattic/node-canvas/commit/2bf76b508cc1b3c891ce6f244d780b2f9a7282a9 / #1784), it's already exported under an alias shown below. I'll see about undoing this.
https://github.com/Automattic/node-canvas/blob/d7ebfcec12682bf7a57bca7aa98ed48398adf4bd/types/index.d.ts#L216

I think what you want is this:
```ts
import {CanvasRenderingContext2D} from "canvas";
CanvasRenderingContext2D.prototype.foo = "bar";
```

**Comment by Tolfx** [comment]
> I think what you want is this:
> 
> ```ts
> import {CanvasRenderingContext2D} from "canvas";
> CanvasRenderingContext2D.prototype.foo = "bar";
> ```

This could have been the cased but I think this will also resolve into a issue which I explained when it comes to declaring it. Because if I would be declaring `CanvasRenderingContext2D` again it would remove all of its methods and only leave what I specify myself to declare, which means I need to rewrite all of the methods again *(copy/paste it)*, which isn't very ethical if the package would have a major or update.

Perhaps there is a fix to it but can't really think of any at the moment.

**Comment by zbjornson** [comment]
Can you provide a full example? Typescript [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) should do what you want, if I understand what you mean.

**Comment by Tolfx** [comment]
> Can you provide a full example? Typescript [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) should do what you want, if I understand what you mean.

```ts
declare module "canvas" {
    export interface CanvasRenderingContext2D {
        hello: string;
    }
}

CanvasRenderingContext2D.prototype.hello = "hello"; // Works fine

...
ctx = canvas.getContext('2d');
ctx.beginPath() // doesn't exist anymore as for example
...
```

Also tried declaration mergin but didn't get it to work.

**Comment by zbjornson** [comment]
`beginPath` is being removed because you're modifying `CanvasRenderingContext2D` instead of `NodeCanvasRenderingContext2D`. This works for me:

```ts
import {CanvasRenderingContext2D} from "canvas";

declare module "canvas" {
	interface NodeCanvasRenderingContext2D {
		hello: string;
	}
}

CanvasRenderingContext2D.prototype.hello = "hi";
CanvasRenderingContext2D.prototype.beginPath();
```

**Comment by Tolfx** [comment]
But does it work while compiled. Why I renamed it to `Context2d` is because once compiled for js it doesn't return a error. Thus asking is `CanvasRenderingContext2D` a valid class that can be used once compiled. Will try once I got time.

**Comment by Tolfx** [comment]
> `beginPath` is being removed because you're modifying `CanvasRenderingContext2D` instead of `NodeCanvasRenderingContext2D`. This works for me:
> 
> ```ts
> import {CanvasRenderingContext2D} from "canvas";
> 
> declare module "canvas" {
> 	interface NodeCanvasRenderingContext2D {
> 		hello: string;
> 	}
> }
> 
> CanvasRenderingContext2D.prototype.hello = "hi";
> CanvasRenderingContext2D.prototype.beginPath();
> ```

Finally tried the method and worked even compiled, so this `PR` can be closed. Thanks for the help. 👍

**Comment by almeidx** [comment]
> `beginPath` is being removed because you're modifying `CanvasRenderingContext2D` instead of `NodeCanvasRenderingContext2D`. This works for me:
> 
> ```ts
> import {CanvasRenderingContext2D} from "canvas";
> 
> declare module "canvas" {
> 	interface NodeCanvasRenderingContext2D {
> 		hello: string;
> 	}
> }
> 
> CanvasRenderingContext2D.prototype.hello = "hi";
> CanvasRenderingContext2D.prototype.beginPath();
> ```

I cannot get this solution to work ever since the 2.9.0 release (which includes https://github.com/Automattic/node-canvas/commit/4a891ef22c5bdf56f3284279d490f53a8f60f396)

**Pull request closed without merging**
