### PR TITLE
Backport contextRendering changes for drawImage

### PR DESCRIPTION
**Pull request by asturur**
Backport the drawImage fix to the 1.6.x branch.

### CODE REVIEW

**Comment by asturur** [comment]
@LinusU @zbjornson Can you restart the node 0.8 build? i think it was a fluke.

I think this PR is ready

**Comment by zbjornson** [comment]
It's continuing to fail during the install step. I don't have time this minute to troubleshoot, but travis might need to use an older version of npm for node 0.8.

**Comment by LinusU** [comment]
Works now 🙌 

Thanks!

**Comment by LinusU** [comment]
Released as 1.6.12 🚀

**Comment by asturur** [comment]
whooo ooo i can write tests in node now instead of browsers!

**Pull request merged**
