### PR TITLE
Bump version to 1.2.4

### PR DESCRIPTION
**Pull request by garthk**
Cuts new release for @LinusU's work:

* Automattic/node-canvas#574 Include paths for #217, #541, #572
* Automattic/node-canvas#583 Travis builds

### CODE REVIEW

**Comment by kangax** [comment]
Someone needs to npm publish (I'm on my phone now)

**Comment by LinusU** [comment]
This is awesome :+1:

**Comment by TooTallNate** [comment]
Published.

**Comment by LinusU** [comment]
Thank you!

**Pull request merged**
