### PR TITLE
package: remove pre-scripts

### PR DESCRIPTION
**Pull request by LinusU**
See discussion in #672.

@rvagg, @kangax would you be sad to see this go?

ping @zbjornson

### CODE REVIEW

**Comment by zbjornson** [comment]
:+1:

(BTW you added the scripts in d4fab578, although they were 1:1-ish replacements for the make targets.)

**Comment by LinusU** [comment]
Yeah, I just added them to do exactly what the make-file did...

**Comment by targos** [comment]
With this change, is it still possible to work on the C++ code and `npm test` without manually recompiling ?

**Comment by LinusU** [comment]
@targos Unfortunately that would no longer work.

The problem is that you don't want that in all instances. I think that "test" should only do testing.

But it would of course be nice to have one command to type when doing development. Some ways to do this would be 1) bash function/alias 2) another npm script, maybe `build-and-test` 3) another npm package that could work with any npm module, it would be installed by the developer with `npm install -g ___`.

**Pull request closed without merging**
