### PR TITLE
Make Context2d's currentTransform configurable

### PR DESCRIPTION
**Pull request by targos**
This allows the library to be used with the jest test runner.

See https://github.com/targos/canvas-jest for a simple repro.

### CODE REVIEW

**Comment by LinusU** [comment]
cool

**Comment by LinusU** [comment]
Do you want this in 1.x as well?

**Comment by zbjornson** [comment]
Does jest actually work with this module at all? I thought it breaks with native dependencies because it tampers with the require cache.

**Comment by targos** [comment]
Thanks!

> Do you want this in 1.x as well?

I think 1.x is not affected by this.

> Does jest actually work with this module at all?

Yes, with this change it works.

**Comment by LinusU** [comment]
Published as 2.0.0-alpha.8

**Pull request merged**
