### PR TITLE
fix #809

### LINKED ISSUE #809: If you call ctx.restore while on the initial state, nothing will get drawn
To reproduce, open any of the examples and add a call to `ctx.restore()` before any other operations on `ctx`. The resulting image will be completely empty, which isn't what happens in the browser

Seems like `cairo_restore` does not check if you're on the initial state for some reason, or maybe it works differently than we expect

Cairo 1.14.6

### PR DESCRIPTION
**Pull request by chearon**
See #809

### CODE REVIEW

**Comment by zbjornson** [comment]
See also #316 ... looks like it has/had the same goal?

**Comment by LinusU** [comment]
Hmm, would it make sense to merge `restore` and `restoreState`? That way we are sure that we don't introduce any new bugs by removing the check from `restoreState`

**Comment by chearon** [comment]
oh yeah you're right, I didn't know about #316 

@LinusU makes sense I'll update in a sec

**Comment by chearon** [comment]
I've merged those functions as requested and updated it to be compatible with #715

**Comment by LinusU** [comment]
Thank you 👍

**Comment by zbjornson** [comment]
Wanna close #316 since this makes it redundant? :)

**Pull request merged**
