### PR TITLE
io.js compatibility

### PR DESCRIPTION
**Pull request by salzhrani**
Tested on node stable and iojs, seems to work fine

### CODE REVIEW

**Comment by salzhrani** [comment]
0.6 is failing but newer versions are green

**Comment by salzhrani** [comment]
@kangax is dropping support for 0.6 an option? It seems many libraries upgrading nan are dropping support for 0.6. If not could an iojs branch possible ?

**Comment by TooTallNate** [comment]
Thanks!

**Comment by salzhrani** [comment]
Would you like another PR with Travis update and a version bump ?

**Comment by TooTallNate** [comment]
v1.2.0 published to npm

**Comment by salzhrani** [comment]
Wow. Thanks.

**Pull request merged**
