### PR TITLE
Add caption overlay on image example

### PR DESCRIPTION
**Pull request by preco21**
Extracted from https://github.com/Automattic/node-canvas/issues/805 but polished a bit.

Original:
image

With caption overlay:
image

### CODE REVIEW

**Comment by LinusU** [comment]
This looks very nice! Would you mind making sure that the code follows [standard style](https://standardjs.com/), that's why Travis is failing. Thanks!

**Comment by preco21** [comment]
Okay, just have polished the code looking way better 😉

**Comment by preco21** [comment]
Oops, hold on there are some unintended changes.

**Comment by preco21** [comment]
@LinusU Sorry for bumping up this again. Could you verify this one more time?

**Pull request merged**
