### PR TITLE
Make setLineDash able to handle full zeroed dashes

### LINKED ISSUE #1055: context.setLineDash([0,0]) stop drawing operations
## Issue or Feature
When using ctx.setLineDash([0,0]), drawing calls done after are ignored.
While setting lineDash to [0,0] is not usefull, the same thing is tolerated by browser canvas.

Whenever this is a backend problem or not, node-canvas could inspect the dash setting for problematic sequences and ignore them in order to provide compatibility with canvas code.

As a side node, node-canvas looks like is tolerating ctx.setLineDash(array); where at least one element is not 0, for example [0, 3, 0] is OK or also [0, 0, 3] even if the resulting dash is slightly different from canvas at the line start.

## Steps to Reproduce
```js
const Canvas = require('canvas');
let { writeFileSync, createWriteStream } = require('fs');
let pngfile = createWriteStream("./bug.png");

const canvas = new Canvas(200, 200)
const ctx = canvas.getContext('2d')
ctx.setLineDash([0,0]);
ctx.fillStyle = 'green';
ctx.fillRect(10,10, 150,150);
ctx.lineWidth = 8;
ctx.strokeStyle = 'red';
ctx.fillStyle = 'blue';
ctx.strokeRect(10,10, 150,150);
ctx.fillRect(10,10, 150,150);
let stream = canvas.createPNGStream();

stream.on("data", function(chunk){
    pngfile.write(chunk);
});
stream.on("end", function(){
    console.log("saved png");
});
```

## Browser fiddle with same code
https://jsfiddle.net/yyg1adr3/

* Version of node-canvas (e.g. 1.6.X):
* Environment (e.g. node 6.9.5 on Mac OS X Sierra):

### PR DESCRIPTION
**Pull request by asturur**
closes #1055

Expanded current test
image

### CODE REVIEW

**Comment by asturur** [comment]
I see build is failing in 1.x branch too. did i do something wrong?

**Comment by chearon** [comment]
I don't think so, looks like a dependency of a dependency that's breaking 😞

**Comment by zbjornson** [comment]
Yeah, 1.x for node 0.12 and earlier has been broken for a while.

**Comment by LinusU** [comment]
Found the issue 😂  https://github.com/Automattic/node-canvas/commit/078a8572d328e6652c28b70039c6df28a046fdbd#r26403732

fix incoming

**Comment by LinusU** [comment]
Would you mind rebasing? That should fix the Travis failure 👌

**Comment by asturur** [comment]
sure!

**Comment by asturur** [comment]
ok green tick

**Comment by zbjornson** [comment]
Ported to 2.x branch (master) in 727cb2cd71325998a394fdb53b5fe5a561e29c90. Thanks!

**Comment by asturur** [comment]
was a pleasure! let me know how to proceed with the othet PR, i have also other things to try to contribute but i would like to settle those first.

**Pull request merged**
